#!/usr/bin/env node
'use strict';

const fs   = require('fs');
const path = require('path');

const QR_PATH = path.resolve(__dirname, '../../data/output/contabo_quick_reference.json');
const OUT_PATH = path.resolve(__dirname, '../../PRICES.md');

if (!fs.existsSync(QR_PATH)) {
  console.error(`ERROR: ${QR_PATH} not found`);
  process.exit(1);
}

const data    = JSON.parse(fs.readFileSync(QR_PATH, 'utf8'));
const plans   = data.plans;
const genAt   = data.generated_at;

const families = {};
for (const p of plans) {
  (families[p.family] = families[p.family] || []).push(p);
}

const lines = [
  '# Contabo Pricing',
  '',
  `> **Last updated:** ${genAt}  `,
  '> Auto-refreshed twice daily · data from [contabo.com](https://contabo.com)',
  '',
];

const eur = (pricing, period) => {
  const v = pricing?.[period]?.effective_monthly;
  return v != null ? `€${Number(v).toFixed(2)}` : '—';
};

for (const [family, fplans] of Object.entries(families)) {
  lines.push(`## ${family}`, '');
  lines.push(
    '| Plan | CPU | RAM | Storage | Port | 1 mo | 6 mo | 12 mo |',
    '|------|-----|-----|---------|------|------|------|-------|',
  );
  for (const p of [...fplans].sort((a, b) => a.plan_family_rank - b.plan_family_rank)) {
    lines.push(
      `| [${p.product_name}](${p.url}) ` +
      `| ${p.cpu_count ?? '—'} vCPU ` +
      `| ${p.ram_gb ?? '—'} GB ` +
      `| ${p.storage_primary_gb ?? '—'} GB ${p.storage_primary_type ?? ''} ` +
      `| ${p.port_speed_mbps ?? '—'} Mbps ` +
      `| ${eur(p.pricing, '1m')} | ${eur(p.pricing, '6m')} | ${eur(p.pricing, '12m')} |`,
    );
  }
  lines.push('');
}

lines.push(
  '---',
  '*Prices in EUR, excl. VAT. Includes default add-ons. Generated by [contabo-pricing-scraper](../../)*',
);

fs.writeFileSync(OUT_PATH, lines.join('\n') + '\n');
console.log(`Generated PRICES.md · ${plans.length} plans · ${genAt}`);
