#!/usr/bin/env python3
import json, sys
from pathlib import Path

QR = Path("data/output/contabo_quick_reference.json")
if not QR.exists():
    sys.exit(f"ERROR: {QR} not found")

data   = json.loads(QR.read_text())
plans  = data["plans"]
gen_at = data["generated_at"]

families = {}
for p in plans:
    families.setdefault(p["family"], []).append(p)

lines = [
    "# Contabo Pricing",
    "",
    f"> **Last updated:** {gen_at}  ",
    "> Auto-refreshed twice daily · data from [contabo.com](https://contabo.com)",
    "",
]

for family, fplans in families.items():
    lines += [f"## {family}", ""]
    lines += [
        "| Plan | CPU | RAM | Storage | Port | 1 mo | 6 mo | 12 mo |",
        "|------|-----|-----|---------|------|------|------|-------|",
    ]
    for p in sorted(fplans, key=lambda x: x["plan_family_rank"]):
        pricing = p.get("pricing", {})
        def eur(k):
            v = pricing.get(k, {}).get("effective_monthly")
            return f"€{v:.2f}" if v is not None else "—"
        lines.append(
            f"| [{p['product_name']}]({p['url']}) "
            f"| {p['cpu_count'] or '—'} vCPU "
            f"| {p['ram_gb'] or '—'} GB "
            f"| {p['storage_primary_gb'] or '—'} GB {p['storage_primary_type'] or ''} "
            f"| {p['port_speed_mbps'] or '—'} Mbps "
            f"| {eur('1m')} | {eur('6m')} | {eur('12m')} |"
        )
    lines.append("")

lines += [
    "---",
    "*Prices in EUR, excl. VAT. Includes default add-ons. "
    "Generated by [contabo-pricing-scraper](../../)*",
]

Path("PRICES.md").write_text("\n".join(lines) + "\n")
print(f"Generated PRICES.md · {len(plans)} plans · {gen_at}")
